Clamidity\AuthNetBundle\Entity\CustomerProfile:
    type: mappedSuperclass
    fields:
        profileId:
            type: integer
            length: 50
        created_at:
            type: datetime
        modified_at:
            type: datetime