Clamidity\AuthNetBundle\Entity\PaymentProfile:
    type: mappedSuperclass
    fields:
        paymentProfileId:
            type: string
            length: 50
        accountNumber:
            type: string
            length: 50
        created_at:
            type: datetime
        modified_at:
            type: datetime