Clamidity\AuthNetBundle\Entity\ShippingAddress:
    type: mappedSuperclass
    fields:
        shippingAddressId:
            type: bigint
            length: 50
        created_at:
            type: datetime
        modified_at:
            type: datetime
        address:
            type: string