Clamidity\AuthNetBundle\Entity\Transaction:
    type: mappedSuperclass
    fields:
        transactionId:
            type: integer
            length: 50
        created_at:
            type: datetime
        modified_at:
            type: datetime