ms2474_authnet_cimprofile_index:
    pattern: /
    defaults: { _controller: Ms2474AuthNetBundle:CIMProfile:index }

ms2474_authnet_cimprofile_new_individual:
    pattern: /new/individual
    defaults: { _controller: Ms2474AuthNetBundle:CIMProfile:newIndividual }

ms2474_authnet_cimprofile_post:
    pattern: /post
    defaults: { _controller: Ms2474AuthNetBundle:CIMProfile:postIndividual }
    requirements:
        _method: POST