clamidity_authnet_cimprofile_index:
    pattern: /
    defaults: { _controller: ClamidityAuthNetBundle:CIMProfile:index }

clamidity_authnet_cimprofile_new_individual:
    pattern: /new/individual
    defaults: { _controller: ClamidityAuthNetBundle:CIMProfile:newIndividual }

clamidity_authnet_cimprofile_post:
    pattern: /post
    defaults: { _controller: ClamidityAuthNetBundle:CIMProfile:postIndividual }
    requirements:
        _method: POST