clamidity_authnet_customerprofile_index:
    pattern: /
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:index }

clamidity_authnet_customerprofile_view:
    pattern: /{id}
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:view }

clamidity_authnet_customerprofile_new_individual:
    pattern: /new/individual
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:newIndividual }

clamidity_authnet_customerprofile_post_individual:
    pattern: /post/individual
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:postIndividual }
    requirements:
        _method: POST

clamidity_authnet_customerprofile_addshippingaddress:
    pattern: /{id}/add_shipping_address
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:addShippingAddress }

clamidity_authnet_customerprofile_postshippingaddress:
    pattern: /{id}/post_shipping_address
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:postShippingAddress }
    requirements:
        _method: POST

clamidity_authnet_customerprofile_transaction_new:
    pattern: /{id}/transaction/new
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:newTransaction }

clamidity_authnet_customerprofile_transaction_post:
    pattern: /{id}/transaction/post
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:postTransaction }
    requirements:
        _method: POST

clamidity_authnet_customerprofile_delete:
    pattern: /{id}/delete
    defaults: { _controller: ClamidityAuthNetBundle:CustomerProfile:delete }
    requirements:
        _method: POST