parameters:
    authorize_net.manager.class: Clamidity\AuthNetBundle\AuthorizeNet\AuthorizeNetManager
    authorize_net.factory.class: Clamidity\AuthNetBundle\AuthorizeNet\AuthorizeNetFactory

services:
    # Factory Class
    authorize_net.factory:
        class: %authorize_net.factory.class%

    # Managers
    authorize_net.manager:
        class: %authorize_net.manager.class%
        factory_service: authorize_net.factory
        factory_method: get
        arguments:
            login_id: %authorize_net.login_id%
            transaction_key: %authorize_net.transaction_key%
            sandbox: %authorize_net.sandbox%
            log_file: %authorize_net.log_file%
    clamidity_authnet.customer.manager:
        class: Clamidity\AuthNetBundle\Entity\CustomerProfileManager
        arguments:
            dispatcher: "@event_dispatcher"
            em: "@doctrine.orm.entity_manager"
            class: %authorize_net.customer_profile_class%

    # Event Subscribers
    clamidity_authnet.customer.add_address_subscriber:
        class: Clamidity\AuthNetBundle\EventListener\CustomerAddressSubscriber
        arguments:
            em: "@doctrine.orm.entity_manager"
            securityContext: "@security.context"
            class: %authorize_net.shipping_address_class%
        tags:
            - { name: kernel.event_subscriber }
    clamidity_authnet.customer.add_paymentprofile_subscriber:
        class: Clamidity\AuthNetBundle\EventListener\CustomerPaymentProfileSubscriber
        arguments:
            em: "@doctrine.orm.entity_manager"
            securityContext: "@security.context"
            class: %authorize_net.payment_profile_class%
        tags:
            - { name: kernel.event_subscriber }
    clamidity_authnet.customer.add_transaction_subscriber:
        class: Clamidity\AuthNetBundle\EventListener\CustomerTransactionSubscriber
        arguments:
            em: "@doctrine.orm.entity_manager"
            securityContext: "@security.context"
            class: %authorize_net.transaction_class%
        tags:
            - { name: kernel.event_subscriber }
    
    # Form Configuration Services
    clamidity_authnet.customerprofile_individual.form:
        class: Clamidity\AuthNetBundle\Form\CustomerProfileIndividualType
        arguments:
            data_class: %authorize_net.customer_profile_class%
    clamidity_authnet.paymentprofile.form:
        class: Clamidity\AuthNetBundle\Form\PaymentProfileType
        arguments:
            data_class: %authorize_net.payment_profile_class%
    clamidity_authnet.shippingaddress.form:
        class: Clamidity\AuthNetBundle\Form\ShippingAddressType
        arguments:
            data_class: %authorize_net.shipping_address_class%
    clamidity_authnet.transaction.form:
        class: Clamidity\AuthNetBundle\Form\TransactionType
        arguments:
            data_class: %authorize_net.transaction_class%