parameters:
    authorize_net.manager.class: Clamidity\AuthNetBundle\AuthorizeNet\AuthorizeNetManager
    authorize_net.factory.class: Clamidity\AuthNetBundle\AuthorizeNet\AuthorizeNetFactory
services:
    authorize_net.factory:
        class: %authorize_net.factory.class%
    authorize_net.manager:
        class: %authorize_net.manager.class%
        factory_service: authorize_net.factory
        factory_method: get
        arguments:
            login_id: %authorize_net.login_id%
            transaction_key: %authorize_net.transaction_key%
            sandbox: %authorize_net.sandbox%
            log_file: %authorize_net.log_file%
    clamidity_authnet.listener.customer_address_creator:
        class: Clamidity\AuthNetBundle\EventListener\CustomerPaymentProfileSubscriber
        arguments:
            em: "@doctrine.orm.entity_manager"
            securityContext: "@security.context"
        tags:
             - { name: kernel.event_subscriber, event: authnet.customer.add_address, method: addPaymentProfile }
    clamidity_authnet.listener.customer_paymentprofile_creator:
        class: Clamidity\AuthNetBundle\EventListener\CustomerAddressSubscriber
        arguments:
            em: "@doctrine.orm.entity_manager"
            securityContext: "@security.context"
        tags:
            - { name: kernel.event_subscriber, event: authnet.customer.add_address, method: addAddress }